FROM nginx:alpine

RUN apk add --no-cache gettext

COPY docker/nginx.conf.template /etc/nginx/nginx.conf.template
COPY ui/index.html /usr/share/nginx/html/index.html

EXPOSE 80

CMD envsubst '${FASTAPI_HOST} ${MLFLOW_HOST}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'
